sudo: false

language: php

php:
  - hhvm
  - 7.0
  - 5.6
  - 5.5
  - 5.4

install:
  - if [[ "$TRAVIS_PHP_VERSION" == '7.0' ]]; then composer require hanneskod/readme-tester:1.0-beta.1 ; fi
  - if [[ "$TRAVIS_PHP_VERSION" != '7.0' ]]; then composer install ; fi

script:
  - phpunit
